---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by bittermann.
--- DateTime: 16.03.2023 01:52
---

function sotTime()
    local hr =
        math.modf((os.date("%H")*60*60+os.date("%M")*60+os.date("%S")) / 60)
    local sr =
        os.date("%S")
    hr = hr - math.modf(hr/24) * 24
    local ho, ap
    if(hr > 12) then
        ho = hr - 12
        ap = "pm"
    else
        ho = hr
        ap = "am"
    end
        return (ho.." : "..sr..ap)
end

sotTime()


